### PR TITLE
openai: add gpt-4o_20240927 (after advanced voice model release)

### PR DESCRIPTION
**Pull request by esauvisky**

### CODE REVIEW

**Comment by 0xeb** [comment]
for both of your PRs, I ask you two things please:

1. make sure you attribute it to the proper author if you are not the one who figured it out. for instance, I attribute elder_plinius in various places
2. make sure you also update the corresponding table of contents file (README.md) and in the proper folder

Finally, how did you verify the work if you are the one who did it?

**Comment by esauvisky** [comment]
I'm the one who figured it out? lol

**Comment by esauvisky** [comment]
screencapture-chatgpt-c-66f653fa-d8bc-8008-bd8a-e2d19916e2ae-2024-09-28-03_34_55

Is this what you want? I don't really care if you accept this PR, honestly, was just trying to help the community.

**Comment by 0xeb** [comment]
We are on the same page. I don't mean to get you on the defensive side here. We both want to help the community and I appreciate your addition.

I am asking to make sure we have accurate stuff we share w/ the community.

So what is left is just to please update the corresponding README file and link your new prompts like it currently is.

Thank you and much appreciated.

**Pull request closed without merging**
